//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.cargps.android.model.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.SurfaceView;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import com.cargps.android.R.layout;
import com.fu.qr_codescan.view.ViewfinderView;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ScanEleCarFragment_
    extends ScanEleCarFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.activity_capture, container, false);
        }
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ScanEleCarFragment_.FragmentBuilder_ builder() {
        return new ScanEleCarFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        openledImg = ((ImageView) hasViews.findViewById(com.cargps.android.R.id.openledImg));
        surfaceView = ((SurfaceView) hasViews.findViewById(com.cargps.android.R.id.surfaceView));
        viewfinderView = ((ViewfinderView) hasViews.findViewById(com.cargps.android.R.id.viewfinderView));
        inputImg = ((ImageView) hasViews.findViewById(com.cargps.android.R.id.inputImg));
        initViews();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<ScanEleCarFragment_.FragmentBuilder_, ScanEleCarFragment>
    {


        @Override
        public ScanEleCarFragment build() {
            ScanEleCarFragment_ fragment_ = new ScanEleCarFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
