//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.cargps.android.model.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Build.VERSION;
import android.os.Build.VERSION_CODES;
import android.os.Bundle;
import android.support.v4.app.ActivityCompat;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.TextView;

import com.cargps.android.R.id;
import com.cargps.android.R.layout;
import com.cargps.android.data.ConsumeOrder;

import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

import java.io.Serializable;

public final class PayActivity_
    extends PayActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String MONEY_EXTRA = "money";
    public final static String YAJIN_EXTRA = "yajin";
    public final static String ORDER_EXTRA = "order";
    public final static String CODE_EXTRA = "code";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_topup_layout);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static PayActivity_.IntentBuilder_ intent(Context context) {
        return new PayActivity_.IntentBuilder_(context);
    }

    public static PayActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new PayActivity_.IntentBuilder_(fragment);
    }

    public static PayActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new PayActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        alipayCb = ((CheckBox) hasViews.findViewById(id.alipayCb));
        timeLayout = hasViews.findViewById(id.timeLayout);
        showMoenyTv = ((TextView) hasViews.findViewById(id.showMoenyTv));
        stopTimeTv = ((TextView) hasViews.findViewById(id.stopTimeTv));
        payBtn = ((Button) hasViews.findViewById(id.payBtn));
        payHintTv = ((TextView) hasViews.findViewById(id.payHintTv));
        startTimeTv = ((TextView) hasViews.findViewById(id.startTimeTv));
        weiXinCb = ((CheckBox) hasViews.findViewById(id.weiXinCb));
        sumTimeTv = ((TextView) hasViews.findViewById(id.sumTimeTv));
        if (payBtn!= null) {
            payBtn.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    PayActivity_.this.payBtn();
                }

            }
            );
        }
        initViews();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(MONEY_EXTRA)) {
                money = extras_.getDouble(MONEY_EXTRA);
            }
            if (extras_.containsKey(YAJIN_EXTRA)) {
                yajin = extras_.getBoolean(YAJIN_EXTRA);
            }
            if (extras_.containsKey(ORDER_EXTRA)) {
                order = ((ConsumeOrder) extras_.getSerializable(ORDER_EXTRA));
            }
            if (extras_.containsKey(CODE_EXTRA)) {
                code = extras_.getString(CODE_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<PayActivity_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, PayActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), PayActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), PayActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    if (VERSION.SDK_INT >= VERSION_CODES.JELLY_BEAN) {
                        fragment_.startActivityForResult(intent, requestCode, lastOptions);
                    } else {
                        fragment_.startActivityForResult(intent, requestCode);
                    }
                } else {
                    if (context instanceof Activity) {
                        Activity activity = ((Activity) context);
                        ActivityCompat.startActivityForResult(activity, intent, requestCode, lastOptions);
                    } else {
                        if (VERSION.SDK_INT >= VERSION_CODES.JELLY_BEAN) {
                            context.startActivity(intent, lastOptions);
                        } else {
                            context.startActivity(intent);
                        }
                    }
                }
            }
        }

        public PayActivity_.IntentBuilder_ money(double money) {
            return super.extra(MONEY_EXTRA, money);
        }

        public PayActivity_.IntentBuilder_ yajin(boolean yajin) {
            return super.extra(YAJIN_EXTRA, yajin);
        }

        public PayActivity_.IntentBuilder_ order(ConsumeOrder order) {
            return super.extra(ORDER_EXTRA, ((Serializable) order));
        }

        public PayActivity_.IntentBuilder_ code(String code) {
            return super.extra(CODE_EXTRA, code);
        }

    }

}
